export const PRODUCT_LIMITS = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 100,
  DESCRIPTION_MIN_LENGTH: 0,
  DESCRIPTION_MAX_LENGTH: 1000,
  CATEGORY_MIN_LENGTH: 2,
  CATEGORY_MAX_LENGTH: 50,
  STOCK_MAX_VALUE: 999999,
  LIMIT_DEFAULT_VALUE: 10,
  LIMIT_MAX_VALUE: 100,
  PAGE_DEFAULT_VALUE: 1,
  SORT_BY_OPTIONS: ["name", "price", "createdAt"],
  SORT_BY_DEFAULT_VALUE: "createdAt",
  ORDER_OPTIONS: ["asc", "desc"],
  ORDER_DEFAULT_VALUE: "asc",
};

export const PRODUCT_MESSAGES = {
  CREATED: "Product created successfully",
};