export const PRODUCT_LIMITS = {
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 100,
    DESCRIPTION_MIN_LENGTH: 0,
    DESCRIPTION_MAX_LENGTH: 1000,
    CATEGORY_MIN_LENGTH: 2,
    CATEGORY_MAX_LENGTH: 50,
    STOCK_MAX_VALUE: 999999,
};